agent_preset: sphereagent_2d_lidar
task_preset: foraging_2000_collision_penalty
# reset_on_stage_change: true  # reinit critic + optimizer at stage transitions

stages:
  - world_presets: [static_rockmaze_foraging]
    steps: 250_000
  - world_presets: [static_rockmaze_foraging]
    steps: 250_000
  - world_presets: [static_rockmaze_foraging]
    steps: 250_000
  - world_presets: [static_rockmaze_foraging]
    steps: 250_000
