agent_preset: sphereagent_2d_lidar_ego
task_preset: volumetric_exploration_1000_collision_penalty
# reset_on_stage_change: true  # reinit critic + optimizer at stage transitions

stages:
  - world_presets: [maze_memorymaze_11x11]
    steps: 500_000
  - world_presets: [maze_memorymaze_11x11]
    steps: 500_000
  - world_presets: [maze_memorymaze_11x11]
    steps: 500_000
  - world_presets: [maze_memorymaze_11x11]
    steps: 500_000
  - world_presets: [maze_memorymaze_11x11]
    steps: 500_000
  - world_presets: [maze_memorymaze_11x11]
    steps: 500_000
  - world_presets: [maze_memorymaze_11x11]
    steps: 500_000
  - world_presets: [maze_memorymaze_11x11]
    steps: 500_000
  - world_presets: [maze_memorymaze_11x11]
    steps: 500_000
  - world_presets: [maze_memorymaze_11x11]
    steps: 500_000
  - world_presets: [maze_memorymaze_11x11]
    steps: 500_000
  - world_presets: [maze_memorymaze_11x11]
    steps: 500_000
  - world_presets: [maze_memorymaze_11x11]
    steps: 500_000
  - world_presets: [maze_memorymaze_11x11]
    steps: 500_000
  - world_presets: [maze_memorymaze_11x11]
    steps: 500_000
  - world_presets: [maze_memorymaze_11x11]
    steps: 500_000
  - world_presets: [maze_memorymaze_11x11]
    steps: 500_000
  - world_presets: [maze_memorymaze_11x11]
    steps: 500_000
  - world_presets: [maze_memorymaze_11x11]
    steps: 500_000
  - world_presets: [maze_memorymaze_11x11]
    steps: 500_000
